### PR TITLE
Update the role for changes in `cisagov/ansible-role-cyhy-core`

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This pull request makes updates to the role to provide necessary interoperability with changes in the [cisagov/ansible-role-cyhy-core] dependency.

## 💭 Motivation and context ##

This is a sibling pull request to https://github.com/cisagov/ansible-role-cyhy-core/pull/79 to ensure we can pass necessary arguments to the downstream [cisagov/ansible-role-geoip2] dependency.

## 🧪 Testing ##

Automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

[cisagov/ansible-role-cyhy-core]: https://github.com/cisagov/ansible-role-cyhy-core
[cisagov/ansible-role-geoip2]: https://github.com/cisagov/ansible-role-geoip2

### CODE REVIEW

**Comment by dv4harr10** [comment]
Hi Nick @mcdonnnj, one question: should the requirements.yml file at ansible-role-ncats-webd/meta/requirements.yml contain the role: " name: ncats_webd and src: https://github.com/cisagov/ansible-role-ncats-webd " as stated in the README file? I noticed the other role listed there " name: cyhy_core and src: https://github.com/cisagov/ansible-role-cyhy-core."

**Review by dv4harr10 — APPROVED** [review]

**Comment by mcdonnnj** [comment]
> Hi Nick @mcdonnnj, one question: should the requirements.yml file at ansible-role-ncats-webd/meta/requirements.yml contain the role: " name: ncats_webd and src: https://github.com/cisagov/ansible-role-ncats-webd " as stated in the README file? I noticed the other role listed there " name: cyhy_core and src: https://github.com/cisagov/ansible-role-cyhy-core."

The `meta/requirements.yml` lists dependencies for this role that are not included in the `dependencies` block of `meta/main.yml`. Due to how [cisagov/ansible-role-cyhy-core] is used we must explicitly install it as part of the role's tasks and so it must be declared as a dependency in the `meta/requirements.yml` file.

[cisagov/ansible-role-cyhy-core]: https://github.com/cisagov/ansible-role-cyhy-core

**Review by dav3r — APPROVED** [review]
LGTM!

Have you applied the updated user Terraform yet?  If so, please mention that somewhere in this PR.  If not, please mention when you are planning to do that.

**Comment by mcdonnnj** [comment]
> LGTM!
> 
> Have you applied the updated user Terraform yet? If so, please mention that somewhere in this PR. If not, please mention when you are planning to do that.

@dav3r Sorry i didn't think to list it because the tests will not pass without the Terraform being applied.

**Pull request merged**
